### ISSUE TITLE
Could not find the main class

### ISSUE THREAD

**Issue by dyejunior** [Baralga/baralga#10]
I'm having the same issue with standalone and installed version. When I launch, I get the message "Could not find the main class: org-remast.baralga.gui.BaralgaMain. Program will exit."

I downloaded today's current version. I'm running Java 7u55 on a Win8 PC. I tried installing at the root of C:, which was throwing requests for admin permission and then in a "My Documents" subfolder.

**Comment by remast** [comment]
Seems to work for others so I would not know what to do. Might have been fixed in a newer version.
