### ISSUE TITLE
Unable to install/use/clean on Windows 8.1

### ISSUE THREAD

**Issue by Yurand** [Baralga/baralga#15]
I tried baralga-installer-1.7.6.jar:

1) Installer complains about write access to "C:\Program Files (x86)\" (I can install other soft without problems)
2) I installed it in (C:\Install\baralga)
3) On first run it asked me for location of "baralga-core-1.7.6.jar", then It show me error window with the following:

Could not find the main class: org.remast,baralga,gui.BaralgaMain.
Program will exit 

4) I can't find it in program list to uninstall it

**Comment by gal9000** [comment]
Same Problem here 2day.
I Created C:\APPS\baralga and installed it there.
Got Problem to Start it from Baralga Icon on Desktop but solved it by linking it to installed executable in C:\APPS\baralga\baralga-core-1.7.6.jar. Seems to work now but I am still testing.

**Comment by imsoftware** [comment]
The ticket is 5 years old and market share of windows 8.1 has dropped. @gal9000 @Yurand can you reproduce the problem today?

**Comment by Treer** [comment]
This is Windows 10 (10.0.19041)
I tried both the installer and the standalone

![baralga](https://user-images.githubusercontent.com/6390507/83374214-4574c780-a40e-11ea-91e1-45f84676ca7e.png)

The Java runtime is 
Java(TM) 6 Update 26 (6.0.260)
