### ISSUE TITLE
Minimize on Windows 7 destroys start bar icon

### ISSUE THREAD

**Issue by misterashley** [Baralga/baralga#16]
When I minimize the application in Windows 7, the icon for the app disappears. I see an icon in the tray, but there is no option to restore the main program window.

If I try to run the application again I get a 'locked database' error as you might expect.

I have to close the tray icon and run the application again to see the main window.

Minimize doesn't mean close. :)

**Comment by gschenck** [comment]
Just click the tray icon twice to restore  the main program window.
