### ISSUE TITLE
After installation, there are no shortcuts on the desktop and in startup

### ISSUE THREAD

**Issue by mrkaban** [Baralga/baralga#50]
Installed version 1.8.3 and did not find shortcuts on the desktop and in the start menu. Not all users will be able to find the program in the "program files."

Ready to help with the translation of the interface into Russian.

**Comment by mrkaban** [comment]
I use the operating system Windows 10 x64 1909. The application itself works without problems.

**Comment by remast** [comment]
@mrkaban If you would help tranlating into russion that would be great. What you need to do is translate the file https://github.com/Baralga/baralga/blob/master/baralga-core/src/main/resources/org/remast/baralga/gui/GuiTexts.properties which contains all texts.

**Comment by mrkaban** [comment]
Here is the translated file, only I should check it in the program.
[GuiTexts.zip](https://github.com/Baralga/baralga/files/4717312/GuiTexts.zip)

**Comment by remast** [comment]
@mrkaban I just created a pull request https://github.com/Baralga/baralga/pull/52 with your translation. You can contact me at baralga(AT)geekmail.de and I can send you a test version if you like.

**Comment by mrkaban** [comment]
Some problems with the encoding! Here is a screenshot! The shortcut on the desktop and in the start menu also does not appear.
![Снимок](https://user-images.githubusercontent.com/14289360/86772778-e0506980-c07e-11ea-8db7-07b329f12b60.png)

**Comment by mrkaban** [comment]
The file that I threw off from you opens without problems. file encoding - Utf-8.

**Comment by remast** [comment]
Oh, ok. I just tested it with the version 1.8.4 portable. The encoding seems fine but some texts are missing, e.g. in the export dialogs.

![grafik](https://user-images.githubusercontent.com/914776/86775605-cea79b80-c057-11ea-93c3-14c5721f352b.png)

Which version are you using? And which java version do you have installed? (You can find that out with `java -version`).

**Comment by mrkaban** [comment]
I have such a problem with both versions, both portable and installation.

Here is a screenshot. Windows 10 64 bit.
![Снимок](https://user-images.githubusercontent.com/14289360/86777887-ee54b900-c083-11ea-8833-f0d6289aa137.png)

**Comment by mrkaban** [comment]
maybe there is a problem in the utf-8 encoding? in windows by default windows-1251

**Comment by remast** [comment]
I checked on the same windows version but my Java version is `openjdk version "11.0.7" 2020-04-14`.

**Comment by remast** [comment]
@mrkaban could you check with Java 11?

**Comment by mrkaban** [comment]
I confirm the solution to the problem. Can you solve this problem in any other way? It's just that it will be very difficult for users with a very low level of training to explain that you need to install not just a Java library, but Java developer tools (JDKs).

**Comment by remast** [comment]
Sure, I will look into it. Testing with a different java version was just to reproduce the error. I'll check out how to resolve this.

**Comment by remast** [comment]
@mrkaban I just realized that by mistake I have not given you all texts for translation. Here are the missing texts:
[baralga-texts-ru.zip](https://github.com/Baralga/baralga/files/4929762/baralga-texts-ru.zip)

I will convert all i18n properties files back to ASCII to make it work with java 8 which is supported until end of 2020 (see https://en.wikipedia.org/wiki/Java_version_history).

**Comment by mrkaban** [comment]
Got it, okay, I'll translate the specified files! One of these days I'll try to do it. Today I can't, I'm very tired at work.

**Comment by mrkaban** [comment]
I have translated, attach the archive. I'm not sure that all the labels will fit, therefore, if possible, I would like to see how it will look in the program, so that if there are such problems, I would correct the labels.
[baralga-texts-ru.zip](https://github.com/Baralga/baralga/files/4943713/baralga-texts-ru.zip)

**Comment by remast** [comment]
Great thanks. I have created a pre-release for you to test at https://github.com/Baralga/baralga/releases/tag/v1.8.5-alpha.

**Comment by mrkaban** [comment]
Everything seems to be all right!

**Comment by mrkaban** [comment]
please correct in one of the following versions, I translated one line incorrectly, and did not notice it right away.
[GuiTexts_ru.zip](https://github.com/Baralga/baralga/files/4975000/GuiTexts_ru.zip)

**Comment by mrkaban** [comment]
Thank you for the program! Special thanks for distributing it under the license of GNU LGPL!

Added a program to a Russian-language site about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BE%D1%84%D0%B8%D1%81/%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/baralga-%D0%BE%D1%82%D1%81%D0%BB%D0%B5%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8.html)).

There are no more questions, I close the ticket. Then, as time will be, please correct the translation, the file was sent earlier.
