### ISSUE TITLE
syncing accross multiple PCs

### ISSUE THREAD

**Issue by Rik44444** [Baralga/baralga#51]
more a question than an issue: do people have experience with syncing Baralga accross multiple PCs ? DOes it work well with dropbox, for example?

**Comment by Rik44444** [comment]
Linked to this: I'd like to make automatic backups of the Baralga data. Where are the data stored? There appears to be a data folder, but with me that folder is empty. I know it is possible to export manually, but i'm talking about automatic backups now (e.g. via Dropbox).

**Comment by remast** [comment]
If you use the portable version of Baralga all data is stored in a directory named "data" right next to the application itself. This is what you need to store Baralga in Dropbox including all data. In normal mode Baralga stores all data in your user home directory which would not be synced.

**Comment by Rik44444** [comment]
ok brilliant thanks, I'll install the portable version. Thanks again for developing/maintaining this great app!

**Comment by Rik44444** [comment]
hi, for future reference, i sync my files with Pcloud, and when i tried doing this with the Portable version, I got file version conflicts. Using the regular Baralga however, and syncing the Baralga data in my User folder worked without any conflicts. Thanks again for the great app
