### ISSUE TITLE
Installer stuck at 0% progress.

### ISSUE THREAD

**Issue by Claudius10** [Baralga/baralga#58]
Hello.

I have downloaded the 1.8.5 installer from the website, I select the installation destination, accept the thingy, and then the Pack installation progress and Overall installation progress are stuck at the beginning. The bars don't move and the installer is stuck and I have to end the app using Task Manager. I'm using Win 10. Any more info I could provide? 

If anyone could help, I'd be grateful! Thanks!

**Comment by remast** [comment]
Hi, 

actually the Java version and distribution (Oracle, OpenJDK) would be helpful. Since the installer is java based many users experience problems lately I'm arfraid.

Thanks,
Jan

**Comment by remast** [comment]
The best way to diagnose is if you install using the command line with `java -jar Baralga-Installer-1.8.5.jar`.

**Comment by Claudius10** [comment]
Hey.

I typed java -version in CMD and it outputs openjdk version "11.0.8" 2020-07-14. Not sure if this is what you were asking for. I also typed java -jar Baralga-Installer-1.8.5.jar in CMD but it says Error: Unable to access jarfile Baralga-Installer-1.8.5.jar. If there's anything more I can help with, let me know.

**Comment by remast** [comment]
Hm. Running `java -jar Baralga-Installer-1.8.5.jar` should start the installer. This works if the Baralga-Installer-1.8.5.jar is in the current directory. You can check that on Windows using the `dir` command.

**Comment by Claudius10** [comment]
I'm not very familiar with Windows CMD commands unfortunately. I have the installer on my desktop. I'm guessing I need to place it in a folder, select the folder using a command then use the java -jar command. Could you provide a list with all the necessary commands to try and see if starts the installer? Thanks!

**Comment by remast** [comment]
Fixed
