### ISSUE TITLE
how to install this?

### ISSUE THREAD

**Issue by bam80** [Baralga/baralga#90]
It seems is not mentioned in the Readme

**Comment by remast** [comment]
Which operating system are you using? The installer works best on windows.

**Comment by bam80** [comment]
I use Linux

**Comment by rrpegasus** [comment]
Just double-click on the .jar file of the portable edition - assuming you have Java installed - and you're good to go.

For a *portable* version on Windows that doesn't require administrative rights, create a .bat file like the following (adapt the directories, of course):
@echo off
set JAVA_HOME=%USERPROFILE%\usr\jdk11
"%JAVA_HOME%\bin\java" -Xmx64m -jar "%USERPROFILE%\usr\baralga\baralga.jar"

**Comment by bam80** [comment]
Should we write it in Readme?

**Comment by remast** [comment]
That would be nice! Will you make a PR?

**Comment by bam80** [comment]
I won't, sorry.
